---
abstract: "get Ivan Bessarabov's sleep data"
author:
  - 'Ivan Bessarabov <ivan@bessarabov.ru>'
build_requires:
  Test::More: 0
  open: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bessarabv-Sleep
requires:
  Carp: 0
  JSON: 0
  LWP::Simple: 0
  Time::Local: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/bessarabov/Bessarabv-Sleep/issues
  homepage: https://github.com/bessarabov/Bessarabv-Sleep
  repository: https://github.com/bessarabov/Bessarabv-Sleep.git
version: 1.0.0
